### PR TITLE
[ci skip] adding user @xylar

### LINKED ISSUE #2: @conda-forge-admin, please add user @xylar
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Latest version not merged, and this may be a potential issue for Apache Airflow

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added user @xylar as instructed in #2.

Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.

Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.

Fixes #2

### CODE REVIEW

**Comment by xylar** [comment]
@sodre, would you be willing to add me as a maintainer?

**Comment by xylar** [comment]
@conda-forge/core, could you please merge this so I can maintain this feedstock?  Thanks!

**Comment by hmaarrfk** [comment]
Thanks for your patience and willingness to help!

**Comment by xylar** [comment]
@hmaarrfk, Thank you!  Much appreciated!

**Pull request merged**
